### ISSUE TITLE
WithHumanTime API

### ISSUE THREAD

**Issue by sfpprxy** [patsnapops/noop#4]
https://github.com/patsnapops/noop/pull/3#issuecomment-1552771676

**Comment by Yaocool** [comment]
already supported these features in new [pr](https://github.com/patsnapops/noop/pull/5)

**Comment by zhoushoujianwork** [comment]
HumanTime value is never change after init. @Yaocool

**Comment by Yaocool** [comment]
> HumanTime value is never change after init. @Yaocool

already fixed in [pr](https://github.com/patsnapops/noop/pull/9) @zhoushoujianwork
